### ISSUE TITLE
Support 'deferred loading'

### ISSUE THREAD

**Issue by westlinkin** [slang-i18n/slang#135]
When using Flutter Web, all the translations go into `main.dart.js`, making this file very big. So the web app loads very slowly the first time user opens it. But most users will only use one (two at most) translations.

Is Slang support `deferred loading`? making each translation into separate  files, only loading them if needed

**Comment by Tienisto** [comment]
Flutter has this [feature](https://docs.flutter.dev/perf/deferred-components) but it seems that we cannot check if this is loaded yet.

Only `loadLibrary` is not enough as all translation access is non-async so there needs to be a mechanism to fallback to the base translations.

**Comment by westlinkin** [comment]
We can just load the <target locale> and <base locale> together, (if target locale === base locale, then only need to load one locale file). If the user switches to another locale, just load that file.

**Comment by Tienisto** [comment]
yes, but what should `String a = t.myTranslation` return? This getter is not a future.

**Comment by westlinkin** [comment]
the < base locale > is always loaded, just use the < base locale >'s tranlation. after other tranlsation's is downloaded,  reload the correct translations. Is that ok?

**Comment by Tienisto** [comment]
Thinking about this again, I think that this is technically possible. But don't expect this feature soon as I don't have much time for this.

**Comment by Tienisto** [comment]
Added in `4.0.0-dev.1`
