### ISSUE TITLE
Possibility to remove unused translations

### ISSUE THREAD

**Issue by spydon** [slang-i18n/slang#141]
**Motivation**
Currently it is possible to get a list of unused translations, but there is no way (as far as I know) to automatically remove those translation strings.

**Developer Experience**
It would be amazing to be able to run a command locally (similar to `apply`) to remove all unused translations and also be able to run that in your pipeline to check that there aren't any unused translations.
I guess `analyze` could be used for the last part already, but it would be nice to get a command similar to a format checker that returns non-zero on changes.

**Comment by Tienisto** [comment]
Added in `v3.25.0`
