### ISSUE TITLE
`locale` resets after closing and opening the app

### ISSUE THREAD

**Issue by baimamboukar** [slang-i18n/slang#143]
**Describe the bug**

My active locale resets when I close and reopen the app.
- I'm persisting my rawLocale 'fr', 'en', and 'de' using `hydrated_bloc`
- The raw locale is being persisted pretty fine
- But when I close and reopen the app, the active locale resets itself and goes to fallback locale, which is 'en', Meanwhile my persisted raw locale is pretty fine

This is my app.dart
```dart
BlocBuilder<ThemeCubit, bool>(
        builder: (BuildContext context, bool isDarkMode) {
          return BlocBuilder<LanguageCubit, String>(
            builder: (context, lang) {
              return MaterialApp.router(
                theme: theme.toThemeData(Brightness.light),
                //theme: FlexThemeData.light(scheme: FlexScheme.hippieBlue),
                darkTheme: theme.toThemeData(Brightness.dark),
                themeMode: isDarkMode ? ThemeMode.dark : ThemeMode.light,
                localizationsDelegates: AppLocalizations.localizationsDelegates,
                supportedLocales: AppLocaleUtils.supportedLocales,
                locale: Locale(lang), // was TranslationProvider.of(context).flutterLocale
                routerConfig: _router.config(
                  navigatorObservers: () => <NavigatorObserver>[
                    FirebaseAnalyticsObserver(
                      analytics: FirebaseAnalytics.instance,
                    ),
                    EliteRouterObserver(),
                  ],
                ),
                debugShowCheckedModeBanner: false,
              );
            },
          );
        },
      ),
```
This is how I wrapped my MaterialApp widget with `TranslationProvider`
```dart
await runZonedGuarded(
    () async => runApp(
      TranslationProvider(
        child: await builder(),
      ),
    ),
    (error, stackTrace) => log(error.toString(), stackTrace: stackTrace),
  );
```

**To Reproduce**
1. Wrap material with `TranslationProvider`
2. use `TranslationProvider.of(context)flutterLocale`  as MaterialApp locale's attribute
3. Persist your locale
4. Trigger interaction that changes active locale
5. The locale is changed

**Expected behavior**
The locale changes and updates screen, but when you close and reopen app, the locale is reset and goes to fallback locale

**Comment by Tienisto** [comment]
Please provide a minimal example so we are sure that the bug is in the library and not in your application code.

The official [example](https://github.com/Tienisto/slang/blob/master/slang/example/lib/main.dart) works when we minimize and resume the app.

If you don't mean resume but actually "start", then check if `LocaleSettings.setLocaleRaw` works. If it works, then the library part is done. A possible errors are `LocaleSettings.setLocaleRaw` doesn't get called or get called with a wrong value.

**Comment by Tienisto** [comment]
Closed due to inactivity.
