### ISSUE TITLE
Localize custom plugins

### ISSUE THREAD

**Issue by MrNB0dy** [slang-i18n/slang#145]
is it possible to use slang to localize custom plugins?
Are there any examples?

Thanks

**Comment by fzyzcjy** [comment]
> is it possible to use slang to localize custom plugins?

Yes. I do localize my (internal) packages as well as my app.

**Comment by Tienisto** [comment]
Basically, you just create your translation files and access them with the generated global translation variable (`t` by default).

If the package consumer also uses slang, then your package also uses the correct locale.

If the package consumer don't use slang, then you need to have some initialization process to get the current locale

**Comment by MrNB0dy** [comment]
> 
First of all, thank you for your response.
Using the global variable with the files generated in the individual packages via `flutter pub run slang` I encounter the error _"Please wrap your app with "TranslationProvider"_ because my material app is wrapped only with its own TranslationProvider (my app and my custom packages use slang) and not those of the packages. 
I can't figure out how to proceed...

**Comment by Tienisto** [comment]
A workaround is to access the static variable instead of context based variable

**Comment by Tienisto** [comment]
@MrNB0dy, a little bit late but someone else want to do the same thing: #155 

Basically, you need to wrap your app with multiple `TranslationProvider` (one for each package):

```dart
void main() {
  runApp(
    package1.TranslationProvider(
      child: package2.TranslationProvider(child: const MyApp()),
    ),
  );
}
```

Then you would create an extension method on `BuildContext` for each package:

```dart
// implement inside package1
extension Package1TranslationsExt on BuildContext {
  Package1Translations get package1 => Translations.of(this);
}
```

Finally, you can access the translations from each package while enjoying rebuilds on locale change:

```dart
Widget build(BuildContext context) {
  String a = context.package1.my.translation;
  String b = context.package2.another.translation;
}
```
