### ISSUE TITLE
`slang edit add` always puts items at the end

### ISSUE THREAD

**Issue by adil192** [slang-i18n/slang#158]
## Motivation
> Why do you want this feature? Ex: I'm always frustrated when [...]

Putting OUTDATED translations at the end results in messy hard-to-read git diffs.

For example, see https://github.com/adil192/saber/commit/eed1be52641f3f69c04689ac903404c4ff2fe9e8. Only two strings were actually changed, but it's very hard to see that just from looking at the diff:
<img src="https://github.com/slang-i18n/slang/assets/21128619/24f51c39-0ca3-4845-a518-4078a9b11047" width=600>

## Developer Experience
> How should devs use this new feature? Ex: There should be a new parameter called [...]

There should be no change in usage

**Comment by Tienisto** [comment]
I cannot reproduce this. It replaces entries in place and skips not existent keys on my examples

**Comment by adil192** [comment]
> skips not existent keys

Are you referring to missing keys or `(OUTDATED)` keys?

**Comment by Tienisto** [comment]
The outdated keys

**Comment by adil192** [comment]
Hmmm... maybe it only affects yaml?

**Comment by adil192** [comment]
Turns out it's not the OUTDATED flag that's the problem.

Running e.g. `dart run slang edit add fr greetings.hello "Bonjour"` always puts the new translation at the end rather than in the order of the base locale.
