### ISSUE TITLE
Enum with csv ?

### ISSUE THREAD

**Issue by bounty1342** [slang-i18n/slang#159]
Hi,

How can we write the following with css format ?
{
  "greet(context=GenderContext, param=gender)": {
    "male": "Hello Mr",
    "female": "Hello Ms"
  }
}

Is there a way to use Enum with csv, or limited to json ?

Thanks :)

**Comment by Tienisto** [comment]
Hello, you can take a look at the integration tests:

https://github.com/slang-i18n/slang/blob/main/slang/test/integration/resources/main/csv_en.csv

Here is an example:

```csv
"onboarding.greet2(context=GenderContext, param=gender).male",Hello Mr
"onboarding.greet2(context=GenderContext, param=gender).female",Hello Ms
```
