### ISSUE TITLE
Allow combining context and rich text

### ISSUE THREAD

**Issue by tomwyr** [slang-i18n/slang#168]
(Not sure if it's a bug or feature request)

It'd be helpful in certain situations to be able to combine context and rich text together, so that the developer can pass enum to the generated localization functions and style specific part of the text.

Having the following _i18n.json_
```json
{
  "animal(rich, context=Animal)": {
    "dog": "That's a ${text(dog)}.",
    "cat": "That's a ${text(cat)}."
  }
}
```
I'd like to be able to then style the animal's name part
```dart
t.animal(
  context: Animal.cat,
  text: (name) => TextSpan(
    text: name,
    style: const TextStyle(fontWeight: FontWeight.bold),
  ),
);
```
It _kinda_ works right now because the generated code allows to style the variable part but, at the same time, it generates a required parameter that's not even used by the function:
```dart
TextSpan animal({required Animal context, required InlineSpan Function(Animal) contextBuilder, required InlineSpanBuilder text}) {
  switch (context) {
    case Animal.dog:
      return TextSpan(children: [
        const TextSpan(text: 'That\'s a '),
        text('dog'),
        const TextSpan(text: '.'),
      ]);
    case Animal.cat:
      return TextSpan(children: [
        const TextSpan(text: 'That\'s a '),
        text('cat'),
        const TextSpan(text: '.'),
      ]);
  }
}
```

**Comment by Tienisto** [comment]
Thank you. This actually similar to plurals (there you have `nBuilder`). This parameter might be used to show the actual number or enum in the string. But you are right, we can remove this parameter if it's not used.

Fixed in `v3.25.0`
