### ISSUE TITLE
.of(context) returns a concrete type instead of abstraction

### ISSUE THREAD

**Issue by subzero911** [slang-i18n/slang#169]
![image](https://github.com/slang-i18n/slang/assets/12999702/96c5cb26-bd03-4ce0-baba-45226f8a1a8c)
.of() method always returns a generated _StringsRu type which doesn't extend the base Translation type.

I cannot put the retrieved value into a variable because of it:
<img width="382" alt="image" src="https://github.com/slang-i18n/slang/assets/12999702/dafae636-b16f-490c-adfd-54f1d48faec3">

It also hinders me to put the a Translations variable into business-logic controllers.
I had to to pass the whole BuildContext instead.
<img width="504" alt="image" src="https://github.com/slang-i18n/slang/assets/12999702/72c47b14-2645-4c98-b331-1294cd9f1d54">

**Comment by Tienisto** [comment]
Hello, `_StringsRu` is actually the base class but you can set `translation_class_visibility: public` to store the translation values into a separate variable. This removes the underscore making it public.

For more information, you can look into https://github.com/slang-i18n/slang#-dependency-injection

**Comment by subzero911** [comment]
But I need not the StringsRu variable, but Translations variable (which will be a StringsRu or StringsEn depending on the current locale).

**Comment by Tienisto** [comment]
Assuming that `Translations.of(context)` returns `StringsRu`, it seems that `StringsRu` is the base class in your project. If you look into the declaration of `StringsEn`, you will notice that it implements `StringsRu`.
So to wrap up: `Translations.of(context)` will either return `StringsEn` or `StringsRu`, but because `StringsRu` is the base class, the method return type is `StringsRu`
 
`Translations` is just a meaningless class that only provides a nice name.

**Comment by subzero911** [comment]
<img width="384" alt="image" src="https://github.com/slang-i18n/slang/assets/12999702/27de5324-0a53-42cc-a760-3bcd848a443f">

Yup, `ru` is my base and currently the only locale.
So, I can make a variable of StringsRu type and StringsEn, StringsDe, etc., will fit into it. Got it!  

It 98% solved my issue.
The only possible problem: if I change the base locale in `slang.yaml` one day, I will have to change StringsRu type across the whole project.
My proposal it to use `Translations` as a base type.
So even if I change the base local, it won't break the whole system.

**Comment by Tienisto** [comment]
Currently, it is quite useful to be `StringsEn extends StringsRu` so it becomes obvious that English translations fallbacks to Russian.

There is however a workaround to avoid a potential refactoring in the future. You could use `typedef` and rename it to `Translations`:

```dart
typedef Translations = StringsRu;

// Translations.of(context) cannot be used anymore, so we can use the longer version
Translations t = InheritedLocaleData.of<AppLocale, StringsRu>(context).translations;

// "Translations" type works the same way as StringsRu
t.loginPage.name;
```

**Comment by subzero911** [comment]
You could refactor Translations, so `.of(context)` will return a Translations type.
And with codegen power we can add all _StringsRu fields to it. So it will satisfy to its _StringsRu subclass.

<img width="668" alt="image" src="https://github.com/slang-i18n/slang/assets/12999702/38b3e3cb-0511-4de1-aa07-bd2de4f7de89">

_StringsRu implements the Translations

<img width="836" alt="image" src="https://github.com/slang-i18n/slang/assets/12999702/02489ddc-b75d-4f45-946f-56ffb5c15062">

**Comment by Tienisto** [comment]
Good idea, I will look into this

**Comment by subzero911** [comment]
To sum it up, as a user, I expect that X.of(context) will return the instance of X type. It's not natural, that it returns something else (especially some weird private type).

Please note,
1) There's an implicit cast in .of method (the value of _StringsRu is casted to `Translations` return value).
2) You can now get rid of private constructor and use abstract interface class.
Private constructor means that the class is just a holder for some static members.
`abstract` means that class is supposed to be subclassed, `interface` restricts it to be implemented only (not extended).

**Comment by Tienisto** [comment]
Thinking of this issue again, I think we can just rename `_StringsRu` to `Translations` and
add `typedef StringsRu = Translations;` for those who currently use the class name.

If we add the translations to the `Translations` interface, then the generated file could be unecessary big.

**Comment by subzero911** [comment]
I am agree, Translations currently is just a holder for `.of` method, and all the functionality lies in the _StringsRu, so we probably can just move the  `.of` method to the _StringsRu

**Comment by Tienisto** [comment]
Relased in `v3.26.0`
