### ISSUE TITLE
It will cause parsing errors when there are commas in the translation.

### ISSUE THREAD

**Issue by debugerer** [slang-i18n/slang#172]
**Describe the bug**
Thank you for the powerful features provided by this plugin. It works very well most of the time. But I found a problem, and don't know how to resolve. If there are commas in the translation csv file, It will parse incorrectly.

**To Reproduce**
1.  The test csv file is as below:
Key,en,ja,zh-Hans-CN,zh-Hant,es,ru,pt,de,ko,fr
ok,OK,わかりました,好的,好的,DE ACUERDO,ХОРОШО,OK,OK,좋아요,D'ACCORD
test,"Hi, test!",こんにちは、テスト！,嗨，测试！,嗨，測試！,"¡Hola, prueba!","Привет, тест!","Oi, teste!","Hallo, Test!","안녕하세요, 테스트!","Salut, test!"

2.  the slang.yaml is as below:
input_directory: assets/i18n/
input_file_pattern: .csv # change to .i18n.yaml for second package

output_directory: lib/gen # defaulting to lib/gen if input is outside of lib/
output_file_name: strings.g.dart # change to strings_b.g.dart for second package
timestamp: false

3. run commands: dart run slang
4.  the generated strings.g.dart file is as below:
 ...
```
extension on _StringsEn {
	dynamic _flatMapFunction(String path) {
		switch (path) {
			case 'ok': return 'OK';
			case 'test': return '"Hi';  //should be "Hi, test!"
			default: return null;
		}
	}
}

extension on _StringsJa {
	dynamic _flatMapFunction(String path) {
		switch (path) {
			case 'ok': return 'わかりました';
			case 'test': return ' test!"'; //should be "こんにちは、テスト！"
			default: return null;
		}
	}
}

extension on _StringsZhHansCn {
	dynamic _flatMapFunction(String path) {
		switch (path) {
			case 'ok': return '好的';
			case 'test': return 'こんにちは、テスト！'; //should be "嗨，测试！"
			default: return null;
		}
	}
}
```
...

All the remaining parsing is out of order.

**Expected behavior**
**A comma surrounded by a pair of double quotation marks should not be used as a separator.**

This should be a general problem. And I am not really familiar with this plugin. Did I miss any configuration? Could someone tell me what parameters can be configured to solve it?  Thanks!

**Comment by Tienisto** [comment]
This is a bug in the csv library.

It seems to check the first cell to enable quotes.

The fixed csv would be:

```csv
"Key",en,ja,zh-Hans-CN,zh-Hant,es,ru,pt,de,ko,fr
ok,OK,わかりました,好的,好的,DE ACUERDO,ХОРОШО,OK,OK,좋아요,D'ACCORD
test,"Hi, test!",こんにちは、テスト！,嗨，测试！,嗨，測試！,"¡Hola, prueba!","Привет, тест!","Oi, teste!","Hallo, Test!","안녕하세요, 테스트!","Salut, test!"
```

**Comment by debugerer** [comment]
This method solves the problem. Thank you very much!
