### ISSUE TITLE
Support complex anchors in yaml

### ISSUE THREAD

**Issue by ChaserVasya** [slang-i18n/slang#178]
```
_templateEnum: &templateEnum
        enumVal1: ''
        enumVal2: ''
        
....
templateUsage(context=...,param=...):
    <<: *templateEnum
    enumVal2: 'some text'
```    
        
error:
`type 'ObjectNode' is not a subtype of type 'StringTextNode' in type cast`

**Comment by Tienisto** [comment]
The merge operator is currently not supported by the [yaml](https://pub.dev/packages/yaml): (see: https://github.com/dart-lang/yaml/issues/121).

**Comment by Tienisto** [comment]
I tried out different anchors and they seem to work out of the box. I guess if the Dart team add support for the merge operator, it should also work when using slang. There is nothing we can do now (except implementing a custom yaml parser which exceeds the scope of this package).
