### ISSUE TITLE
Flutter returns an error on translation key 'default'

### ISSUE THREAD

**Issue by jaycho1214** [slang-i18n/slang#186]
**Describe the bug**
Flutter gives an error if there is a key `default` in a translations.

**To Reproduce**
1. strings.i18n.yaml
```yaml
empty:
  default:
    example: example
```
2. Run `dart run slang`
3. See error

**Expected behavior**
Should be run without any problems

**Additional context**
slang.yaml
```yaml
fallback_strategy: base_locale
input_file_pattern: .i18n.yaml
```

**Comment by Tienisto** [comment]
Please read the error message. It clearly states that `'default' can't be used as an identifier because it's a keyword.`
There is nothing we can do because this is a limitation by the Dart language. Please comment if I missunderstood your problem.
