### ISSUE TITLE
Newlines are lost when overriding translations

### ISSUE THREAD

**Issue by lohnn** [slang-i18n/slang#195]
**Describe the bug**
We have a few texts in the app that are multi-line. Generating and using them works fine in the app.
When we try to override the translation to update the text, the new-lines are escaped out and shows up as literal \n.

**To Reproduce**
1. Create translation file that contains newlines in the texts
2. Generate and run in the app
3. Override the texts that contains newlines

**Properly generated code works as expected:**
```json
{
  "customerService": {
    "title": "Customer service",
    "openHours": "Office: closed\nChat: All days 8-23"
  }
}
```
![image](https://github.com/slang-i18n/slang/assets/960157/d8870806-5de8-4f67-8ecb-20c0aa54b98f)

**Overriding text escapes the newlines `\n`:**
```Dart
final translation = {
  'customerService': {
    'title': 'Customer service',
    'openHours': 'Office: Week days 7-23\nChat: All days 8-23',
  },
};
LocaleSettings.overrideTranslationsFromMap(
  locale: AppLocale.en,
  isFlatMap: false,
  map: translation,
);
```
![image](https://github.com/slang-i18n/slang/assets/960157/a14c8a1e-733e-4aa3-9c14-54ac1b7b24ad)

The same issue occurs for both `LocaleSettings.overrideTranslations` and `LocaleSettings.overrideTranslationsFromMap`

**Expected behavior**
Newlines show up as expected in the app, such as:
![image](https://github.com/slang-i18n/slang/assets/960157/c5a5fdb4-30e3-4f60-b93a-5ca042dab72c)

**Comment by Tienisto** [comment]
I cannot reproduce this error. Be aware that JSON supports `\n` natively so you might accidentally escape this as an input to the overrides

**Comment by lohnn** [comment]
I could try to create a minimal reproducible repo and link it here if it would help? :)

**Comment by Tienisto** [comment]
What file type do you use? I can see inconsistencies when parsing YAML (`\n` are lost) and CSV (`\n` are escaped)

**Comment by lohnn** [comment]
I've tested using JSON as well as using `overrideTranslationsFromMap`, which takes a Dart map.

**Comment by lohnn** [comment]
Hmm, testing this in a self-contained example, it seems to work. I'll check a bit more and see if I can figure out what's what and get back to you!

**Comment by lohnn** [comment]
You know what?!
It seems to have been fixed between the version that we apparently ran (and I totally forgot to update - slang: ^3.22.0) and the current version. It is now working perfectly as intended.

I apologise for wasting your time and thank you very much for looking at it.

Closing due to PEBCAK.
