### ISSUE TITLE
Arabic translations glitch

### ISSUE THREAD

**Issue by ulullul** [slang-i18n/slang#196]
Hello, I've just decided to use your package for an application but unfortunately encountered a problem with Arabic translations.

When I try to change the language to Arabic, there is a glitch (the video is slowed down a bit):

https://github.com/slang-i18n/slang/assets/46851597/19f17acf-d2f1-496f-96a2-f87d8ced4987

This reproduces only on the web and with any font, including the default one. For Android and IOS, it works fine. 

Hope for your help, many thanks.

**Comment by Tienisto** [comment]
slang only provides the strings. It is up to the developer how to display the strings.

It seems to be a general issue with Flutter
