### ISSUE TITLE
Automatic translation with ChatGPT

### ISSUE THREAD

**Issue by offline-first** [slang-i18n/slang#198]
I have found a cool plugin, unfortunately it only works with arb https://pub.dev/packages/flutter_arb_translator.
Would be nice if there was something like this in the slang plugin.

**Comment by Tienisto** [comment]
Have you tried [slang_gpt](https://pub.dev/packages/slang_gpt)?

**Comment by offline-first** [comment]
Great, you're the best!

**Comment by offline-first** [comment]
Great, you're the best!
