### ISSUE TITLE
[Analyze] RichText json key re-appreared regardless translated in all locales in _missing_translations_...json file

### ISSUE THREAD

**Issue by honghai2196** [slang-i18n/slang#199]
**Describe the bug**

**To Reproduce**
0. Prequisite: 2 locales: `en_US.json and vi_VN.json`
1. Add a richtext key translation in en_US.json: "test_feature(rich)": "Test feature {name}"
2. Add a richtext key translation in vi_VN.json: "test_feature(rich)": "Tính năng thử nghiệm {name}"
3. Run missing analyze command: `dart run slang analyze --split-missing`
4. The key `test_feature(rich): "Test feature {name}"` is still appeared in file `_missing_translations_vi_VN.json`

**Expected behavior**
The key `test_feature(rich): "Test feature {name}"` is disappeared.

**Actual behavior**
<img width="2672" alt="Screenshot 2024-03-14 at 3 39 57 PM" src="https://github.com/slang-i18n/slang/assets/24835894/5852109d-9c3b-4886-8614-a92c54324510">

**Additional context**

**Comment by bawahakim** [comment]
What's the reason this was closed? I have a similar problem, where keys with modifiers are duplicated after running `dart run slang apply`.

E.g.

```
// en
    "couponValidations(map)": {
      "CouponNotExist": "There is no box with this code",
      "CouponAlreadyUsed": "You have already claimed this box",
      "CouponLimitReached": "Too late! This box has no more claims available",
      "CouponExpired": "Too late! This box has expired"
    },
//fr
    "couponValidations(map)": {
      "CouponNotExist": "There is no box with this code",
      "CouponAlreadyUsed": "You have already claimed this box",
      "CouponLimitReached": "Too late! This box has no more claims available",
      "CouponExpired": "Too late! This box has expired"
    },
    "couponValidations": { <-- This object gets added after running `slang apply`
      "CouponNotExist": "There is no box with this code",
      "CouponAlreadyUsed": "You have already claimed this box",
      "CouponLimitReached": "Too late! This box has no more claims available",
      "CouponExpired": "Too late! This box has expired"
    }
```
