### ISSUE TITLE
What is the better way to provide translation across app in a multiple plugin project?

### ISSUE THREAD

**Issue by SAGARSURI** [slang-i18n/slang#203]
Hey @Tienisto 

I have a flutter project with multiple local feature packages in it. I was going through your documentation regarding [multiple packages](https://pub.dev/packages/slang#-multiple-packages). I see that we need to wrap the `MaterialApp` with multiple `TranslationProvider` which can make the widget tree look really weird and deeply nested. What are the other better alternatives to this approach?

**Comment by Tienisto** [comment]
Currently, there is no other solution
