### ISSUE TITLE
Could slang works with showTimePicker & showDatePicker?

### ISSUE THREAD

**Issue by iwhy** [slang-i18n/slang#206]
The reason for this problem is:
    because I used only slang, but not inited Localizations in MaterialApp.   

In most cases, use only slang is enough for i18n strings.  But showTimePicker() and showDatePicker do not support costomized UI Strings. 

Shall there a way to achive this? 

Till now i Just want to define custom widgets to replace those buildin funtions.

**Comment by Tienisto** [comment]
Please check the documentation (specifically step 4a): https://pub.dev/packages/slang#getting-started

You need to add `flutter_localizations` dependency and add it to `localizationsDelegates`.

**Comment by Tienisto** [comment]
Closed due to inactivity
