### ISSUE TITLE
Upon upgrading Flutter from version 3.13.4 to 3.19.4, specifying only variables as values in JSON ceased to convert them to strings.

### ISSUE THREAD

**Issue by chocoyama** [slang-i18n/slang#207]
**Describe the bug**
Upon upgrading Flutter from version 3.13.4 to 3.19.4, specifying only variables as values in JSON ceased to convert them to strings.

**To Reproduce**
1. Add the following definition to a json file:
    ```json
    "hoge": "{hoge}",
    ```
2. The following Dart code is generated:
    ```dart
    String hoge({required Object hoge}) => hoge;
    ```
3. When trying to execute, the following error occurs:
```
ib/i18n/strings.g.dart:634:64: Error: A value of type 'Object' can't be returned from a function with return type 'String'.
 - 'Object' is from 'dart:core'.
  String hoge({required Object hoge}) => hoge;
```

**Expected behavior**
Previously, the following code was generated:
```dart
String hoge({required Object hoge}) => '$hoge';
```

**Additional context**

**Comment by Tienisto** [comment]
Thank you.
This bug has been fixed in `3.30.2`
