### ISSUE TITLE
Support enumName without case conversion

### ISSUE THREAD

**Issue by sladomic** [slang-i18n/slang#208]
Hi and thanks for the awesome package!

We use [ProtobufEnums](https://pub.dev/documentation/protobuf/latest/protobuf/ProtobufEnum-class.html) in our project which we would like to import as contexts. They are always generated in the form of `Example_Enum` with an underline in between.

The problem right now is, that the enumName is changed to pascal case and therefore it regenerates the enum even though we set generate_enum to false.

It's about this line of code. Could we either remove it or have it as a config?

https://github.com/slang-i18n/slang/blob/266523faeac1d3ee4d6b72d759931456593430e6/slang/lib/builder/builder/raw_config_builder.dart#L121

**Comment by Tienisto** [comment]
Yes, we can remove it
