### ISSUE TITLE
Support ARB placeholder types

### ISSUE THREAD

**Issue by snipd-mikel** [slang-i18n/slang#214]
**Motivation**
ARB files can already be used with slang, which allows to use the default Flutter format. However, the placeholder type is ignored when generating code

```dart
"nWombats": "{count} wombats",
  "@nWombats": {
    "placeholders": {
      "count": {
        "type": "int"
      }
    }
  }
```

Generates 

```dart
String nWombats({required Object count}) => '${count} wombats';
```

We could use `"nWombats": "{count:int} wombats"` to specify the type, but that format is not supported by some tools and is not part of the ARB file format.

**Developer Experience**
Support ARB placeholder type parameter.

Thanks for your work!

**Comment by Tienisto** [comment]
Added in v3.31.0
