### ISSUE TITLE
How to make a language switcher?

### ISSUE THREAD

**Issue by simplenotezy** [slang-i18n/slang#221]
When calling `LocaleSettings.setLocale(locale);` nothing happens unless I click "Hot reload".

How can I have the views update when changing language?

**Comment by simplenotezy** [comment]
Found: https://github.com/slang-i18n/slang/issues/37

The solution is to use `final t = Translations.of(context);` instead. This should probably be documented.

**Comment by Tienisto** [comment]
Hi, this is already documented in https://pub.dev/packages/slang#-changing-locale
