### ISSUE TITLE
Full analyze command ignores inner translation usage

### ISSUE THREAD

**Issue by ChaserVasya** [slang-i18n/slang#222]
**Describe the bug**
analyze option have undesired behaviour.

**To Reproduce**
```
  "personBirthdayNotification(context=DatesRelation, param=relation)": {
    "inPast": "У клиента было день рождения @:days назад",
    "inFuture": "У клиента через @:days день рождения",
    "now": "У клиента сегодня день рождения"
  },
  "days": {
    "one": "$n день",
    "few": "$n дня",
    "many": "$n дней",
    "other": "$n дней"
  },
```
`days` is not used in source code, but used in `personBirthdayNotification`.

run analyze --full
_unused_translation.json have next lines
```
    "days": {
      "one": "$n день",
      "few": "$n дня",
      "many": "$n дней",
      "other": "$n дней"
    }
```

**Expected behavior**
After I run `analyze --full`, run `clean`, all is ok, no analyzer warning.

**version**
3.29.0

**Comment by Tienisto** [comment]
This should be fixed in 3.31.1
