### ISSUE TITLE
When and where should I use setPluralResolver?

### ISSUE THREAD

**Issue by sed1ka** [slang-i18n/slang#223]
Thanks for great localizations library

I got an exception message
`Resolver for <lang = id> not specified! Please configure it via LocaleSettings.setPluralResolver. A fallback is used now.`

The explanation in #167 is not clear enough for me.

So where and when should I use setPluralResolver?

Currently, I only used `t.<localtizationsKey>` directly
```
class ExampleView extends StatelessWidget {
  const ExampleView({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(t.name),
      ),
    );
  }
}
```

and with `final t = AppLocalizations.of(context);` in `build` method,
```
class ExampleView extends StatelessWidget {
  const ExampleView({super.key});

  @override
  Widget build(BuildContext context) {
  final t = AppLocalizations.of(context);

    return Scaffold(
      appBar: AppBar(
        title: Text(t.name),
      ),
    );
  }
}
```

Based on #167, do you mean I need to always call `setPluralResolver` after using any LocaleSettings?
Example like:

```
// Set the local
LocaleSettings.setLocale(_);
// Then I need to set the plural resolver after
LocaleSettings.setPluralResolver(_);
```

Or can I ignore the exception warning? because `_defaultResolver` on [plural_resolver_map.dart](https://github.com/slang-i18n/slang/blob/main/slang/lib/api/plural_resolver_map.dart#L6 ) was enough for me.

If my assumptions are wrong, please tell me correctly when and where I should use setPluralResolver.
Please provide examples to be very helpful. Thanks

**Comment by Tienisto** [comment]
Hello, you can call `LocaleSettings.setPluralResolver` anywhere before accessing. For example, I am initializing it before creating the `MaterialApp`.

For example

```dart
void main() {
  WidgetsFlutterBinding.ensureInitialized();

  LocaleSettings.setPluralResolver(...); // before any translation access is good enough

  LocaleSettings.useDeviceLocale();

  runApp(TranslationProvider(
    child: MyApp(),
  ));
}
```

**Comment by sed1ka** [comment]
Thanks for the quick response.
But after looking deeply, I think it's fine to ignore the exception at least the `_defaultResolver` on [plural_resolver_map.dart](https://github.com/slang-i18n/slang/blob/main/slang/lib/api/plural_resolver_map.dart#L6) is enough for my case.
