### ISSUE TITLE
Class 'Translations' can't define static member 'of' and have instance member 'Translations.of' with the same name (version 3.26.0 and above)

### ISSUE THREAD

**Issue by WieFel** [slang-i18n/slang#233]
**Describe the bug**
From version `3.26.0` or above of `slang` and `slang_flutter`, I get the following error in the file `strings.g.dart`:
```
Class 'Translations' can't define static member 'of' and have instance member 'Translations.of' with the same name.  Try renaming the member to a name that doesn't conflict.
```
Not sure if this has anything to do with my configuration. But if I use version `3.25.0` or below, I don't get any error.

**To Reproduce**
1. Use version `3.26.0` or above of `slang` and `slang_flutter`
2. Run `dart run slang`
3. See the error in `strings.g.dart`

**Expected behavior**
No errors in `strings.g.dart` after generating the file.

**Additional context**
<details>
  <summary>flutter doctor</summary>
  
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-IT)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] VS Code (version 1.90.2)
[✓] Connected device (4 available)            
[✓] Network resources

• No issues found!
  ```
</details>

**Comment by Tienisto** [comment]
Yeah, `of` is now reserved because it is used as a function. So please rename it to another key like `of_`, `ofStr`.

**Comment by WieFel** [comment]
@Tienisto but as far as I understand, I shouldn't edit generated files, should I?

**Comment by Tienisto** [comment]
@WieFel yeah, you should edit the source file if possible. I've added `of` to the list of reserved keywords, so it will be sanitized to `kOf` in `v4.4.1`.
