### ISSUE TITLE
baseLocale selected over language matches when there is no country code match

### ISSUE THREAD

**Issue by manuramosdev** [slang-i18n/slang#241]
I have seen this in the iOS simulator.

- In the device settings, I am able to select "French" with no country specified.
- The Flutter code (`WidgetsBinding.instance.platformDispatcher.locale`) returns "fr_ES", which is weird, but the same thing happens with "fr_CA"
- My app locales are "es", "fr_FR", and "fr_BE".

Inspecting the code, I see that:

1. There is no exact match
2. There is more than one candidate that matches the langaugeCode
3. There is a non-null countryCode to match
4. No candidate matches the countryCode
5. baseLocale is returned at singleton.dart:109 (in my case, "es") 

Is this expected behavior? Should the first candidate of the same language take precedence over the baseLocale?
Should I report that "fr_ES" weird thing to the Flutter team?

Thanks for your work.

**Comment by Tienisto** [comment]
Thank you. This is indeed a bug. Fixed in `v3.31.2`
